# True colors mode
# Add truecolor support
set-option -ga terminal-overrides ",*:Tc"
# Default terminal is 256 colors
set -g default-terminal "tmux-256color"

# Statusbar has white on black/transparent background
set -g status-bg default
set -g status-fg default

set -g @online_icon "ON"
set -g @offline_icon "OFF"

set -g status-right-length 65
set -g status-left-length 15

setw -g window-status-format " #I #W "
setw -g window-status-current-format " #I #W "
setw -g window-status-current-style fg=black,bg=colour48

set -g mouse on

# Changing prefix from 'Ctrl+b' to 'Ctrl+a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Quick reload
bind r source-file ~/.tmux.conf

# Splitting terminals using | and -, move to previous working dir
unbind '"'
unbind %
bind - split-window -h -c '#{pane_current_path}'
bind | split-window -v -c '#{pane_current_path}'

# Move panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
